[project]
package-mode = false
name = "grocery-store"
version = "0.1.0"
description = "A grocery store application"
authors = [
    {name = "mercury", email = "122353133+kostya1102m@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic==1.13.3",
    "sqlalchemy[asyncio]==2.0.35",
    "pydantic==2.9.2",
    "pydantic-settings==2.5.2",
    "asyncpg>=0.29.0",
    "jinja2==3.1.4",
    "uvicorn==0.34.0",
    "fastapi[all]==0.115.6",
    "starlette==0.41.3",
    "trio==0.23.2",
    "anyio==4.7.0",
    "pytest==7.4.4",
    "h11==0.14.0",
    "style==1.1.0",
    "attrs==24.2.0",
    "wheel==0.45.0",
    "PySocks==1.7.1",
    "pycryptodome==3.20.0",
    "pillow==11.0.0",
    "filelock==3.16.1",
    "pyasn1==0.6.1",
    "Mako==1.3.8",
    "Pygments==2.17.2",
    "MarkupSafe==3.0.2",
    "rich==13.7.0",
    "markdown-it-py==3.0.0",
    "PyYAML==6.0.2",
    "typing-extensions==4.12.2",
    "sniffio==1.3.0",
    "outcome==1.3.0.post0",
    "six==1.16.0",
    "click==8.1.7",
    "mdurl==0.1.2",
    "certifi==2024.8.30",
    "pydantic-core==2.23.4",
    "websockets==14.1",
    "wsproto==1.2.0",
    "greenlet==3.1.1",
    "Cython==0.29.28",
    "annotated-types==0.7.0",
    "itsdangerous==2.2.0",
    "pyreadline3==3.4.1",
    "python-dotenv==1.0.1",
    "loguru==0.7.0",
    "python-jose==3.3.0",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"