"""remove picked_products table

Revision ID: eab323436b77
Revises: 5dc1ec61d8f6
Create Date: 2024-12-17 23:35:24.947547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql, __all__, mysql

# revision identifiers, used by Alembic.
revision: str = 'eab323436b77'
down_revision: Union[str, None] = '5dc1ec61d8f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('picked_products')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('picked_products',
                    sa.Column('product_id', sa.Integer(), nullable=False),
                    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['product_id'], ['ordered_products.product_id'], ),
                    sa.PrimaryKeyConstraint('product_id')
                    )
    # ### end Alembic commands ###
